# Generated by Django 3.1.3 on 2020-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_env', '0005_auto_20201211_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '失效'), (1, '有效')], default=1, verbose_name='环境状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '失效'), (1, '有效')], default=1, verbose_name='项目状态'),
        ),
    ]
