# Generated by Django 3.1.3 on 2020-12-08 11:04

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_env', '0001_initial'),
        ('apitest', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('taste_id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务ID')),
                ('taste_name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('taste_time', models.DateTimeField(auto_now_add=True, verbose_name='任务日期')),
                ('description', models.CharField(max_length=50, verbose_name='任务描述')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_env.environment', verbose_name='环境名称')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.plan', verbose_name='计划名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_env.project', verbose_name='项目名称')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名称')),
                ('passward', models.CharField(max_length=20, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_env.project', verbose_name='项目名称')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
