# Generated by Django 3.1.3 on 2020-12-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_env', '0001_initial'),
        ('taste_user', '0002_taste_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'RUNNING'), (0, 'STOP')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='project_env.project', verbose_name='项目名称'),
        ),
    ]
