# Generated by Django 3.1.3 on 2020-12-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_env', '0002_auto_20201210_0937'),
        ('taste_user', '0004_auto_20201210_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passward',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_env.project', verbose_name='项目名称'),
            preserve_default=False,
        ),
    ]
