# Generated by Django 3.1.3 on 2020-12-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_env', '0003_auto_20201210_0959'),
        ('taste_user', '0005_auto_20201210_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_env.project', verbose_name='项目名称'),
        ),
    ]
