# Generated by Django 3.1.3 on 2020-12-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0007_auto_20201211_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'STOP'), (1, 'RUNNING')], default=0, verbose_name='任务状态'),
        ),
        migrations.RemoveField(
            model_name='taste',
            name='user',
        ),
        migrations.AddField(
            model_name='taste',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='taste_user.user', verbose_name='负责人'),
            preserve_default=False,
        ),
    ]
