# Generated by Django 3.1.3 on 2020-12-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0008_auto_20201211_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='plan',
            field=models.TextField(verbose_name='计划名称'),
        ),
    ]
