# Generated by Django 3.1.3 on 2020-12-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
        ('taste_user', '0009_auto_20201211_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.plan', verbose_name='计划名称'),
        ),
    ]
