# Generated by Django 3.1.3 on 2020-12-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0010_auto_20201211_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taste',
            name='user',
        ),
    ]
