# Generated by Django 3.1.3 on 2020-12-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0011_remove_taste_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taste',
            name='plan',
        ),
        migrations.AddField(
            model_name='taste',
            name='plans',
            field=models.TextField(default=1, verbose_name='测试计划'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'RUNNING'), (0, 'STOP')], default=0, verbose_name='任务状态'),
        ),
    ]
