# Generated by Django 3.1.3 on 2020-12-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0013_auto_20201213_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'RUNNING'), (0, 'STOP')], default=0, verbose_name='任务状态'),
        ),
    ]
