# Generated by Django 3.1.3 on 2020-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0014_auto_20201214_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'STOP'), (1, 'RUNNING')], default=0, verbose_name='任务状态'),
        ),
    ]
