# Generated by Django 3.1.3 on 2020-12-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0015_auto_20201214_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'RUNNING'), (2, 'PAUSE'), (0, 'STOP'), (3, 'RESUME')], default=0, verbose_name='任务状态'),
        ),
    ]
