# Generated by Django 3.1.3 on 2020-12-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0016_auto_20201216_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'PAUSE'), (0, 'STOP'), (1, 'RUNNING'), (3, 'RESUME')], default=0, verbose_name='任务状态'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('permissions', models.ManyToManyField(to='taste_user.Permission')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='taste_user.Role'),
        ),
    ]
