# Generated by Django 3.1.3 on 2021-01-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0017_auto_20201227_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(3, 'RESUME'), (1, 'RUNNING'), (2, 'PAUSE'), (0, 'STOP')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taste',
            name='taste_time',
            field=models.CharField(max_length=30, verbose_name='任务日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='邮箱号'),
        ),
    ]
