# Generated by Django 3.1.3 on 2020-12-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0013_auto_20201213_1721'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taste_user.taste', verbose_name='报告对应的任务'),
            preserve_default=False,
        ),
    ]
