# Generated by Django 3.1.3 on 2020-12-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20201214_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.plan', verbose_name='报告对应的计划'),
        ),
    ]
